const Groq = require("groq-sdk");
const { z } = require("zod");
const { zodResponseFormat } = require("openai/helpers/zod");
const puppeteer = require("puppeteer");

const groq = new Groq({
    apiKey: process.env.GROQ_API_KEY
});

const interviewReportSchema = z.object({
    matchScore: z.number(),
    technicalQuestions: z.array(z.object({
        question: z.string(),
        intention: z.string(),
        answer: z.string()
    })),
    behavioralQuestions: z.array(z.object({
        question: z.string(),
        intention: z.string(),
        answer: z.string()
    })),
    skillGaps: z.array(z.object({
        skill: z.string(),
        severity: z.enum(["low", "medium", "high"])
    })),
    preparationPlan: z.array(z.object({
        day: z.number(),
        focus: z.string(),
        tasks: z.array(z.string())
    })),
    title: z.string()
});

const resumePdfSchema = z.object({
    htmlContent: z.string().describe("The HTML content of the resume")
});

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {
    const prompt = `Generate an interview report for a candidate with the following details:
Resume: ${resume}
Self Description: ${selfDescription}
Job Description: ${jobDescription}

Provide:
- matchScore: a score from 0-100 indicating how well the candidate matches the job
- technicalQuestions: an array of technical interview questions, each with the question, the interviewer's intention, and how to answer it
- behavioralQuestions: an array of behavioral interview questions, each with the question, the interviewer's intention, and how to answer it
- skillGaps: an array of skill gaps with severity (low/medium/high) the candidate should work on
- preparationPlan: a day-wise preparation plan with day number, focus area, and tasks for each day`;

    const response = await groq.chat.completions.create({
        model: "openai/gpt-oss-120b",
        messages: [
            { role: "user", content: prompt }
        ],
        response_format: zodResponseFormat(interviewReportSchema, "interview_report")
    });

    const result = JSON.parse(response.choices[0].message.content);
    console.log(JSON.stringify(result, null, 2));
    return result;
}

async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle0" });
    const pdfBuffer = await page.pdf({ format: "A4", margin:{
        top:"20mm",
        bottom:"20mm",
        left:"15mm",
        right:"15mm"
    } });
    await browser.close();
    return pdfBuffer;
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
    const prompt = `Generate a resume PDF for a candidate with the following details:
Resume: ${resume}
Self Description: ${selfDescription}
Job Description: ${jobDescription}

the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
The content of resume should not sound like it's generated by AI and should be as close as possible to a real human-written resume.
You can highlight the content using some colors or different font styles but the overall design shouls be simple and professional.
The content should be ATS friendly i.e. it should be easily parsable by ATS systems without losing important information.
The resume should not be so lengthy , it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and makes sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.`;

    const response = await groq.chat.completions.create({
        model: "openai/gpt-oss-120b",
        messages: [
            { role: "user", content: prompt }
        ],
        response_format: zodResponseFormat(resumePdfSchema, "resume_pdf")
    });

    const jsonContent = JSON.parse(response.choices[0].message.content);
    const pdfBuffer = await generatePdfFromHtml(jsonContent.htmlContent);
    return pdfBuffer;
}

module.exports = { generateInterviewReport, generateResumePdf, generatePdfFromHtml };